###
### Library API Testing
###

###
### GET /api/v1/libraries
###

GET http://localhost:5000/api/v1/libraries

###
### GET /api/v1/libraries/{library_id}
###

GET http://localhost:5000/api/v1/libraries/1

###
### POST /api/v1/libraries
###

POST http://localhost:5000/api/v1/libraries
Content-Type: application/json

{
  "name": "New Library",
  "location": "Some City"
}

###
### PUT /api/v1/libraries/{library_id}
###

PUT http://localhost:5000/api/v1/libraries/1
Content-Type: application/json

{
  "name": "Updated Library",
  "location": "Updated City"
}

###
### DELETE /api/v1/libraries/{library_id}
###

DELETE http://localhost:5000/api/v1/libraries/1